apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: agentos-infra
  namespace: flux-system
spec:
  interval: 1m
  url: https://codeup.aliyun.com/69c9d859f167bac7fd250e32/HydeZhaoToo/agentos_infra_code.git
  ref:
    branch: litellm_dev
  secretRef:
    name: codeup-credentials
