apiVersion: v1
kind: ConfigMap
metadata:
  name: agentos-values-dev
  namespace: dev
data:
  values.yaml: |
    global:
      imageRegistry: 6alghj85.mirror.aliyuncs.com
      security:
        allowInsecureImages: true
    litellm:
      replicaCount: 1
      image:
        repository: docker.litellm.ai/berriai/litellm
        tag: "main-stable"
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    pgsql-relational:
      primary:
        persistence:
          storageClass: alicloud-disk-topology-alltype
          size: 20Gi
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
