apiVersion: v1
kind: ConfigMap
metadata:
  name: agentos-values-dev
  namespace: dev
data:
  values.yaml: |
    global:
      imageRegistry: agentos-dev-registry.cn-shanghai.cr.aliyuncs.com
      imagePullSecrets:
        - acr-credentials
      security:
        allowInsecureImages: true
    litellm:
      replicaCount: 1
      image:
        repository: agentos-dev-registry.cn-shanghai.cr.aliyuncs.com/agentos/litellm-database
        tag: "main-stable"
      env:
        - name: LITELLM_LOCAL_MODEL_COST_MAP
          value: "True"
        - name: PYTHONUNBUFFERED
          value: "1"
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    pgsql-relational:
      image:
        repository: agentos/postgresql
        tag: "18.3.0-amd64"
      primary:
        containerSecurityContext:
          enabled: true
          runAsUser: 1001
          runAsGroup: 1001
          readOnlyRootFilesystem: false
        persistence:
          storageClass: alicloud-disk-topology-alltype
          size: 20Gi
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
